### ISSUE TITLE
Bio: add Events subview 

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/dm_apps#513]
Add models and unit tests for events subview in bio diversity project

**Comment by stoyelq** [comment]
Need to determine the verbose name for the "Team" lookup + ways of adding multiple people to a team.

**Comment by stoyelq** [comment]
Event's model also needs a name

**Comment by upsonp** [comment]
I would call this event a "Program Event" because it seems to depend on the Program table.

As for adding more than one person to a team. The relationship does seem wonky to me. I can't see how you can create a team as a consistent object and add/remove people to/from. It looks like eacy peron is going to be belong to their own unique team... So what's the point of the team?

If I designed this and a team was required, I would have created a team table with a team name and role and given the personnel table a team_id, or if one person can be on multiple teams, I would have had a join table that took a per_id and a team_id, creating a many-to-many.

I don't think the event table should even optionally have a link to a team, in Shelley's design, if you know the person then you'll know the team, unless it was intended to be a m-to-m relationship, in which case you'd know the person, but not necessarily the team that should be credited.

It's something we'll have to bring up with Shelley.

**Comment by stoyelq** [comment]
Issues around teams are documented and extend beyond this subview, will need to see what Shelley comes up with here and make new ticket if needed.
